=== kwabe007/DM2517/lab-dtd/party.dtd
<!ENTITY Ouml "ร">
<!ENTITY ouml "รถ">

<!ELEMENT party (title, date, starttime, endtime?, arranger, location, price?, OSAdate?, description?, contact?, host*, toastmaster*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT starttime (#PCDATA)>
<!ELEMENT endtime (#PCDATA)>
<!ELEMENT arranger (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price unit CDATA "sek">

<!ELEMENT OSAdate (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT contact (firstname, lastname, phone, email)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT host (firstname, lastname)>

<!ELEMENT toastmaster (firstname, lastname)>

=== kwabe007/DM2517/lab-dtd/party.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE party SYSTEM "party.dtd">
<party>
  <title>Amphiox Gasque</title>
  <date>2001-09-08</date>
  <starttime>18:00:00</starttime>

  <endtime>03:00:00</endtime>
  <arranger>MF</arranger>
  <location>MF</location>
  <price unit="sek">195</price>
  <OSAdate>2001-08-24</OSAdate>
  <description>
    Party for the new students at Medicinska F&ouml;reningen.
  </description>
  <contact>
    <firstname>Berra</firstname>
    
    <lastname>Berrasson</lastname>
    <phone>08-123456</phone>
    <email>berra@mf.ki.se</email>
  </contact>

  <host>
    <firstname>Anna</firstname>
    <lastname>Jerresand-&Ouml;hrstr&ouml;m</lastname>
  </host>
  
  <toastmaster>
    <firstname>Miranda</firstname>
    <lastname>Michanek</lastname>
  </toastmaster>
  <toastmaster>

    <firstname>Johannes</firstname>
    <lastname>Linde</lastname>
  </toastmaster>
</party>
